version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=debdeep
      - MONGO_INITDB_ROOT_PASSWORD=debdeep
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis
    


volumes:
  mongo-db: